name: Continuous Testing

on:
  push:
    branches:
      - 'release/*'

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install UV
        run: pip install uv==0.5.9

      - name: Run Tests
        run: uv run pytest --cov=do_data_utils tests/
