name: Release Testing and Tag

permissions:
  contents: write
  
on:
  push:
    branches:
      - 'release/*'

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: pip install -r requirements_dev.txt

    - name: Run Tests
      run: pytest tests/

    - name: Tag and Push
      if: ${{ success() }}
      run: |
        python -c "import do_data_utils.version as v; print(v.__version__)" > version.txt
        VERSION=$(cat version.txt)
        git tag $VERSION
        git push origin $VERSION
